"""Diffs calc_port.py against tools/ml/parity_scenarios.json (real calc.js output
for the same scenarios, generated by `node parity_scenarios.mjs`). Run this after
any change to calc_port.py or calc.js before trusting calc_port.py as a label source.
"""
import json
import sys
from pathlib import Path

import calc_port as cp

HERE = Path(__file__).parent
TOL = 1e-6


def close(a, b, tol=TOL):
    return abs(a - b) <= tol * max(1.0, abs(a), abs(b))


def check_scenario(idx, row):
    S = row["input"]
    t = cp.tokens_per_month(cp.PURPOSES[S["purpose"]], S["seats"], S["tasks"], S["days"], S["calls"])
    peak_users = cp.peak_concurrent_users(S["seats"], S["concPct"])
    n_thru = cp.nodes_throughput(S["gpu"], S["localModel"], S["util"], S["days"], t["outTok"], S["peak"])
    n_conc = cp.nodes_concurrency(S["gpu"], S["localModel"], S["slaTps"], peak_users)
    n_for = cp.nodes_for(S["gpu"], S["localModel"], S["util"], S["days"], t["outTok"], S["peak"], S["slaTps"], peak_users)

    checks = [
        ("inTok", t["inTok"], row["inTok"]),
        ("outTok", t["outTok"], row["outTok"]),
        ("calls", t["calls"], row["calls"]),
        ("nodeEffTps", cp.node_eff_tps(S["gpu"], S["localModel"]), row["nodeEffTps"]),
        ("peakTps", cp.rate_stats(S["days"], t["outTok"], S["peak"])["peakTps"], row["peakTps"]),
        ("avgTps", cp.rate_stats(S["days"], t["outTok"], S["peak"])["avgTps"], row["avgTps"]),
        ("peakConcurrentUsers", peak_users, row["peakConcurrentUsers"]),
        ("maxStreamsPerNode", cp.max_streams_per_node(S["gpu"], S["localModel"], S["slaTps"]), row["maxStreamsPerNode"]),
        ("nodesThroughput", n_thru, row["nodesThroughput"]),
        ("nodesConcurrency", n_conc, row["nodesConcurrency"]),
        ("nodesFor", n_for, row["nodesFor"]),
        ("nodeMonthlyRun", cp.node_monthly_run(S["opex"], S["sub"]), row["nodeMonthlyRun"]),
        ("nodeCapex", cp.node_capex(S["gpu"], S["disc"]), row["nodeCapex"]),
        ("apiCostSelected", cp.api_cost_selected(S["pin"], S["pout"], t["inTok"], t["outTok"]), row["apiCostSelected"]),
    ]

    ok = True
    for name, got, want in checks:
        if not close(got, want):
            print(f"  scenario {idx} [{S['purpose']}]: MISMATCH {name}: got {got} vs js {want}")
            ok = False
    return ok


def main():
    rows = json.loads((HERE / "parity_scenarios.json").read_text())
    all_ok = True
    for i, row in enumerate(rows):
        ok = check_scenario(i, row)
        all_ok = all_ok and ok
        print(f"scenario {i} [{row['input']['purpose']}]: {'OK' if ok else 'FAILED'}")
    if not all_ok:
        sys.exit(1)
    print(f"\nAll {len(rows)} scenarios match calc.js exactly.")


if __name__ == "__main__":
    main()
